all: ourPlayer.cpp startOurPlayer.cpp ourGame.cpp utils.cpp
	g++ -o ourPlayer_3AI_RandomDepth ourPlayer.cpp startOurPlayer.cpp ourGame.cpp utils.cpp -w -std=c++11

clean:
	find . -name '*.pyc' -delete
